# Codacy configuration: disable Pylint and Revive for Markdown files to avoid false-positive parsing
engines:
  pylint:
    enabled: true
    patterns:
      - pattern: '**/*.md'
        enabled: false
  revive:
    enabled: true
    patterns:
      - pattern: '**/*.md'
        enabled: false

# Optional global excludes (safe to keep Markdown out of lightweight scanners)
exclude_paths:
  - '**/*.md'
